### ISSUE TITLE
Any compress option ?

### ISSUE THREAD

**Issue by mmomasters** [laixintao/mydumper2s3#9]
As everyone knows, with S3 you have to pay for every PUT (file) you upload, so it would be cheaper to compress all in one file and then stream it to S3, is there any --compress option available ?

Thank you for your great work!

**Comment by laixintao** [comment]
Sorry if you need compression, then this tool might be not what you want.
Because this tool is uploading while mydumper is running, and mydumper2s3 intends to use const disk by deleting files after uploading.

I think it is possible by compressing files because they are uploaded separately, but not possible to tar them into only one file.
